// //  // db.collection(currentUser).get().then((snapShot) => {
// //     //   snapShot.docs.map((doc) => {
// //     //     const timestampOwn = getLocation(doc);
// //     //     console.log(timestampOwn);
// //     //     // const df = db.collection(currentUser).where(timestamp,'==',timestampOwn)
// //     //   })
// //     // })


// //     // const getLocation = (doc) => {
// //     //     const latitudeDb = doc.data().latitude;
// //     //     const longitudeDb = doc.data().longitude;
// //     //     if (latitudeDb != undefined && longitudeDb != undefined) {
// //     //       console.log(latitudeDb)
// //     //       console.log(longitudeDb)
// //     //       console.log(l)
// //     //       const location = useGeoLocation();
// //     //       console.log(location);
// //     //       console.log(n)
// //     //       const ans = isPointWithinRadius(
// //     //         { latitude: Number(latitudeDb), longitude: Number(longitudeDb) },
// //     //         { latitude:l,longitude:n },
// //     //         20000
// //     //       );
// //     //       return doc.id;
// //     //     }
// //     //     return false;
// //     //   }



// //    // const databaseRef = firebase.database().ref().child('people');
// //    // const querybaseRef = querybase.ref(databaseRef, ['name', 'age', 'location']);
   
// //    // // Automatically handles composite keys
// //    // querybaseRef.push({ 
// //    // name: 'David',
// //    // age: 27,
// //    // location: 'SF'
// //    // });
   
// //    // // Find records by multiple fields
// //    // // returns a Firebase Database ref
// //    // const queriedDbRef = querybaseRef
// //    // .where({
// //    //    name: 'David',
// //    //    age: 27
// //    // });
   
// //    // // Listen for realtime updates
// //    // queriedDbRef.on('value', snap => console.log(snap));



// // //    export const app = initializeApp(firebaseConfig);
// // // export const database = getFirestore(app);
// // import Head from 'next/head'
// // import styles from '../styles/Home.module.css'
// // import {app , database} from "../firebaseConfig"
// // import { useEffect, useState } from 'react'
// // import { useRouter } from 'next/router'
// // import {
// //   collection , 
// //   addDoc,
// //   getDocs,
// //   getDoc,
// //   doc,
// //   updateDoc,
// //   deleteDoc
// // } from "firebase/firestore"


// // const dbname = "CrudDB 1";
// // export default function Home() {

// //   const databaseRef = collection(database,dbname);
// //   const [name,setName] = useState('');
// //   const [id,setId] = useState(null);
// //   const [age,setAge] = useState(null);
// //   const [isUpdate,setIsUpdate] = useState(false);
// //   const [firedata,setFiredata] = useState([]);
// //   const router = useRouter();  
// //   useEffect(() => {
// //     let token = sessionStorage.getItem('Token');
// //     if(token) getData();
// //     if(!token){
// //         router.push('/register');
// //     }
// //   }, [])

// //   const addData = ()=>{
// //     addDoc(databaseRef,{
// //       name:name,
// //       age:Number(age)
// //     })
// //     .then(()=>{
// //       alert('data sent');
// //       setName('');
// //       setAge(null);
// //       getData();
// //     })
// //     .catch(()=>{
// //       console.error(err);
// //     })
// //   }

// //   const getData = async ()=>{
// //     await getDocs(databaseRef)
// //     .then((response) => {
// //       setFiredata(response.docs.map((data) => {
// //         return{ ...data.data(),id:data.id};
// //       }));
// //     })
// //   }

// //   const getID = (id , name , age) => {
// //     setId(id);
// //     setIsUpdate(true);
// //     setName(name);
// //     setAge(age); 
// //   }
  
// //   const updateFields = () => {
// //     let fieldToEdit = doc(database,dbname,id);
// //     updateDoc(fieldToEdit,{
// //       name:name,
// //       age:Number(age) 
// //     })
// //     .then(() => {
// //       alert('data updated')
// //       setName('')
// //       setAge(null);
// //       setIsUpdate(false);
// //       getData();
// //     })
// //     .catch((err)=>{
// //       console.error(err);
// //     })
// //   }

// //   const deleteDocument = (id) =>{
// //     let fieldToEdit = doc(database,dbname,id);
// //     deleteDoc(fieldToEdit)
// //     .then(() => {
// //       console.log('Data Deleted')
// //       getData();
// //     })
// //     .catch((err)=>{
// //       console.error(err);
// //     })
// //   }

// //   const logout = () => {
// //     sessionStorage.removeItem('Token');
// //     router.push('/register');
// //   }
// //   return (
// //     <div className={styles.container}>
// //       <Head>
// //         <title>Auth</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>

// //       <main className={styles.main}>
// //         <div>
// //           <h1 onClick={logout}>Log Out</h1>
// //         </div>
// //         <h1>Home</h1>
// //         <input 
// //           className={styles.inputBox}
// //           onChange={(e)=>setName(e.target.value)}
// //           value={name} 
// //           type='text'
// //           placeholder='Name'/>
// //         <input
// //           className={styles.inputBox} 
// //           onChange={(e)=>setAge(e.target.value)}
// //           value={age}
// //           type='number'
// //           placeholder='Age'
// //         />
// //         { isUpdate ? (
// //           <button
// //             className={styles.button}
// //             onClick={updateFields}
// //           >Update</button>
// //         )
// //         : (
// //           <button
// //             className={styles.button}
// //             onClick={addData}
// //           >ADD</button>
// //         )

// //       }

// //         <div className={styles.flex}>
// //           {firedata.map((data)=>{
// //             return (
// //               <div>
// //                 <h3>Name: {data.name}</h3>
// //                 <p>Age: {data.age}</p>
// //                 <button 
// //                   className={styles.button}
// //                   onClick={() => getID(data.id,data.name,data.age)}
// //                 >Update</button>
// //                 <button 
// //                   className={styles.button}
// //                   onClick={() => deleteDocument(data.id)}
// //                 >Delete</button>
// //               </div>
// //             )
// //           })}
// //         </div>
// //       </main>
      
// //     </div>
// //   )
// // }


// import { getFirestore, doc } from 'firebase/firestore';
// import { useDocument } from 'react-firebase-hooks/firestore';
// import {db } from "../firebase";
// const FirestoreDocument = () => {
//   const [value, loading, error] = useDocument(
//     doc(db, "OHunMuFpIi9B7S5wRlni"),
//     {
//       snapshotListenOptions: { includeMetadataChanges: true },
//     }
//   );
//   return (
//     <div>
//       <p>
//         {error && <strong>Error: {JSON.stringify(error)}</strong>}
//         {loading && <span>Document: Loading...</span>}
//         {value && <span>Document: {JSON.stringify(value.data())}</span>}
//       </p>
//     </div>
//   );
// };

// export default FirestoreDocument;